name: Deploy Grill The Code To Int

jobs:
  Deploy_int:
    # Define the Github Actions Runner
    runs-on: [road-runner, Linux, X64, medium]
    if: github.ref == 'refs/heads/main'
    steps:
      # Checkout the repo on the Github Actions Runner
      - uses: actions/checkout@v4
      
      # Install "cf" CLI
      - name: Install CF CLI
        run: |
          echo "hola"
         
